//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comrade.Core.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comrade.Core.Messages.BusinessMessage", typeof(BusinessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não atingiu o número minimo de caracteres..
        /// </summary>
        public static string LKUP2001 {
            get {
                return ResourceManager.GetString("LKUP2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro Incluído com Success!.
        /// </summary>
        public static string MSG01 {
            get {
                return ResourceManager.GetString("MSG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro Alterado com Success!.
        /// </summary>
        public static string MSG02 {
            get {
                return ResourceManager.GetString("MSG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro Excluído com Success!.
        /// </summary>
        public static string MSG03 {
            get {
                return ResourceManager.GetString("MSG03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro não Existe!.
        /// </summary>
        public static string MSG04 {
            get {
                return ResourceManager.GetString("MSG04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro encontrado..
        /// </summary>
        public static string MSG05 {
            get {
                return ResourceManager.GetString("MSG05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro já exists para a Unidade, Data e Hora informados. Registro não foi salvo..
        /// </summary>
        public static string MSG06 {
            get {
                return ResourceManager.GetString("MSG06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar salvar o registro no banco de dados, caso o problema persista, por favor entrar em contato com o suporte..
        /// </summary>
        public static string MSG07 {
            get {
                return ResourceManager.GetString("MSG07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro já exists com mesmo code, por favor informe outro code..
        /// </summary>
        public static string MSG08 {
            get {
                return ResourceManager.GetString("MSG08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Code do cargo invalido..
        /// </summary>
        public static string MSG09 {
            get {
                return ResourceManager.GetString("MSG09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor incorreto para o tipo de transação Débito (O valor informado deve ser superior a R$ 3,00)..
        /// </summary>
        public static string MSG10 {
            get {
                return ResourceManager.GetString("MSG10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor incorreto para o tipo de transação Boleto (O valor informado deve ser inferior a R$ 100,00)..
        /// </summary>
        public static string MSG11 {
            get {
                return ResourceManager.GetString("MSG11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor incorreto para o tipo de transação Crédito (O valor informado deve ser entre R$ 130,00 e R$ 890,00)..
        /// </summary>
        public static string MSG12 {
            get {
                return ResourceManager.GetString("MSG12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro já exists com mesmo nome, por favor informe outro nome..
        /// </summary>
        public static string MSG13 {
            get {
                return ResourceManager.GetString("MSG13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro já existe com a mesma tag, por favor informe outra tag..
        /// </summary>
        public static string MSG14 {
            get {
                return ResourceManager.GetString("MSG14", resourceCulture);
            }
        }
    }
}
